import{a as $,S as q,i as a}from"./assets/vendor-B0XWlCgv.js";(function(){const t=document.createElement("link").relList;if(t&&t.supports&&t.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))i(e);new MutationObserver(e=>{for(const r of e)if(r.type==="childList")for(const l of r.addedNodes)l.tagName==="LINK"&&l.rel==="modulepreload"&&i(l)}).observe(document,{childList:!0,subtree:!0});function s(e){const r={};return e.integrity&&(r.integrity=e.integrity),e.referrerPolicy&&(r.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?r.credentials="include":e.crossOrigin==="anonymous"?r.credentials="omit":r.credentials="same-origin",r}function i(e){if(e.ep)return;e.ep=!0;const r=s(e);fetch(e.href,r)}})();async function m(o,t){const i=`https://pixabay.com/api/?key=55893182-8e8d8d313eea42e04d9d959ce&q=${o}&image_type=photo&orientation=horizontal&safesearch=true&per_page=15&page=${t}`;return(await $.get(i)).data}const P=new q(".gallery a",{captionsData:"alt",captionDelay:250}),h=document.querySelector(".gallery"),d=document.querySelector(".loader"),u=document.querySelector(".load-more-btn");function p(o){const t=o.map(({webformatURL:s,largeImageURL:i,tags:e,likes:r,views:l,comments:w,downloads:S})=>`
        <li class="gallery-item">
          <a class="gallery-link" href="${i}">
            <img class="gallery-image" src="${s}" alt="${e}" />
          </a>
          <div class="info">
            <div class="info-item"><b>Likes</b><span>${r}</span></div>
            <div class="info-item"><b>Views</b><span>${l}</span></div>
            <div class="info-item"><b>Comments</b><span>${w}</span></div>
            <div class="info-item"><b>Downloads</b><span>${S}</span></div>
          </div>
        </li>`).join("");h.insertAdjacentHTML("beforeend",t),P.refresh()}function M(){h.innerHTML=""}function y(){d&&d.classList.remove("is-hidden")}function b(){d&&d.classList.add("is-hidden")}function v(){u&&u.classList.remove("is-hidden")}function L(){u&&u.classList.add("is-hidden")}const g=document.querySelector(".form"),B=document.querySelector(".load-more-btn");let c="",n=1,f=0;g.addEventListener("submit",async o=>{if(o.preventDefault(),c=o.target.elements["search-text"].value.trim(),n=1,!c){a.warning({message:"Please enter a search query!",position:"topRight"});return}M(),L(),y();try{const t=await m(c,n);if(t.hits.length===0){a.error({message:"Sorry, there are no images matching your search query. Please try again!",position:"topRight",backgroundColor:"#ef4040",messageColor:"#fff"});return}f=Math.ceil(t.totalHits/15),p(t.hits),n<f?v():a.info({message:"We're sorry, but you've reached the end of search results.",position:"topRight"})}catch(t){console.error(t),a.error({message:"Something went wrong, please try again later.",position:"topRight"})}finally{b(),g.reset()}});B.addEventListener("click",async()=>{n+=1,L(),y();try{const o=await m(c,n);p(o.hits);const t=document.querySelector(".gallery-item");if(t){const s=t.getBoundingClientRect().height;window.scrollBy({top:s*2,behavior:"smooth"})}n<f?v():a.info({message:"We're sorry, but you've reached the end of search results.",position:"topRight"})}catch(o){console.error(o),a.error({message:"Something went wrong, please try again later.",position:"topRight"})}finally{b()}});
//# sourceMappingURL=main.js.map
